# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'historyparser.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_HistoryParserWindow(object):
    def setupUi(self, HistoryParserWindow):
        HistoryParserWindow.setObjectName(_fromUtf8("HistoryParserWindow"))
        HistoryParserWindow.resize(438, 612)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("images/transfer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        HistoryParserWindow.setWindowIcon(icon)
        HistoryParserWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(HistoryParserWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_5 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.textEditHistory = QtGui.QTextEdit(self.groupBox_5)
        self.textEditHistory.setObjectName(_fromUtf8("textEditHistory"))
        self.verticalLayout_5.addWidget(self.textEditHistory)
        self.gridLayout_2.addWidget(self.groupBox_5, 0, 0, 1, 2)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lineEditInputFile = QtGui.QLineEdit(self.groupBox)
        self.lineEditInputFile.setReadOnly(True)
        self.lineEditInputFile.setObjectName(_fromUtf8("lineEditInputFile"))
        self.horizontalLayout_2.addWidget(self.lineEditInputFile)
        self.buttonInputFile = QtGui.QPushButton(self.groupBox)
        self.buttonInputFile.setObjectName(_fromUtf8("buttonInputFile"))
        self.horizontalLayout_2.addWidget(self.buttonInputFile)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lineEditInputFolder = QtGui.QLineEdit(self.groupBox)
        self.lineEditInputFolder.setReadOnly(True)
        self.lineEditInputFolder.setObjectName(_fromUtf8("lineEditInputFolder"))
        self.horizontalLayout.addWidget(self.lineEditInputFolder)
        self.buttonInputFolder = QtGui.QPushButton(self.groupBox)
        self.buttonInputFolder.setObjectName(_fromUtf8("buttonInputFolder"))
        self.horizontalLayout.addWidget(self.buttonInputFolder)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lineEditOutputFile = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditOutputFile.setReadOnly(True)
        self.lineEditOutputFile.setObjectName(_fromUtf8("lineEditOutputFile"))
        self.horizontalLayout_3.addWidget(self.lineEditOutputFile)
        self.buttonOutputFile = QtGui.QPushButton(self.groupBox_2)
        self.buttonOutputFile.setObjectName(_fromUtf8("buttonOutputFile"))
        self.horizontalLayout_3.addWidget(self.buttonOutputFile)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lineEditOutputFolder = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditOutputFolder.setReadOnly(True)
        self.lineEditOutputFolder.setObjectName(_fromUtf8("lineEditOutputFolder"))
        self.horizontalLayout_4.addWidget(self.lineEditOutputFolder)
        self.buttonOutputFolder = QtGui.QPushButton(self.groupBox_2)
        self.buttonOutputFolder.setObjectName(_fromUtf8("buttonOutputFolder"))
        self.horizontalLayout_4.addWidget(self.buttonOutputFolder)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.checkBoxSimpleNames = QtGui.QCheckBox(self.groupBox_3)
        self.checkBoxSimpleNames.setChecked(True)
        self.checkBoxSimpleNames.setObjectName(_fromUtf8("checkBoxSimpleNames"))
        self.verticalLayout_3.addWidget(self.checkBoxSimpleNames)
        self.checkBoxIgnoreBetSize = QtGui.QCheckBox(self.groupBox_3)
        self.checkBoxIgnoreBetSize.setChecked(True)
        self.checkBoxIgnoreBetSize.setObjectName(_fromUtf8("checkBoxIgnoreBetSize"))
        self.verticalLayout_3.addWidget(self.checkBoxIgnoreBetSize)
        self.checkBoxSiteName = QtGui.QCheckBox(self.groupBox_3)
        self.checkBoxSiteName.setChecked(True)
        self.checkBoxSiteName.setObjectName(_fromUtf8("checkBoxSiteName"))
        self.verticalLayout_3.addWidget(self.checkBoxSiteName)
        self.gridLayout_2.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkBoxHeroPlays = QtGui.QCheckBox(self.groupBox_4)
        self.checkBoxHeroPlays.setChecked(True)
        self.checkBoxHeroPlays.setObjectName(_fromUtf8("checkBoxHeroPlays"))
        self.gridLayout.addWidget(self.checkBoxHeroPlays, 0, 0, 1, 1)
        self.checkBoxPreflopOnly = QtGui.QCheckBox(self.groupBox_4)
        self.checkBoxPreflopOnly.setObjectName(_fromUtf8("checkBoxPreflopOnly"))
        self.gridLayout.addWidget(self.checkBoxPreflopOnly, 0, 1, 1, 1)
        self.checkBoxFlopShown = QtGui.QCheckBox(self.groupBox_4)
        self.checkBoxFlopShown.setObjectName(_fromUtf8("checkBoxFlopShown"))
        self.gridLayout.addWidget(self.checkBoxFlopShown, 1, 0, 1, 1)
        self.checkBoxFlopOnly = QtGui.QCheckBox(self.groupBox_4)
        self.checkBoxFlopOnly.setObjectName(_fromUtf8("checkBoxFlopOnly"))
        self.gridLayout.addWidget(self.checkBoxFlopOnly, 1, 1, 1, 1)
        self.checkBoxTurnShown = QtGui.QCheckBox(self.groupBox_4)
        self.checkBoxTurnShown.setObjectName(_fromUtf8("checkBoxTurnShown"))
        self.gridLayout.addWidget(self.checkBoxTurnShown, 2, 0, 1, 1)
        self.checkBoxRiverShown = QtGui.QCheckBox(self.groupBox_4)
        self.checkBoxRiverShown.setObjectName(_fromUtf8("checkBoxRiverShown"))
        self.gridLayout.addWidget(self.checkBoxRiverShown, 2, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_4, 2, 1, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(0, -1, 10, -1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem = QtGui.QSpacerItem(35, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.buttonParse = QtGui.QPushButton(self.centralwidget)
        self.buttonParse.setObjectName(_fromUtf8("buttonParse"))
        self.horizontalLayout_5.addWidget(self.buttonParse)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 3, 0, 1, 2)
        HistoryParserWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(HistoryParserWindow)
        QtCore.QMetaObject.connectSlotsByName(HistoryParserWindow)

    def retranslateUi(self, HistoryParserWindow):
        HistoryParserWindow.setWindowTitle(_translate("HistoryParserWindow", "HandHistoryParser", None))
        self.groupBox_5.setTitle(_translate("HistoryParserWindow", "Input Text", None))
        self.groupBox.setTitle(_translate("HistoryParserWindow", "Additional Input", None))
        self.label_2.setText(_translate("HistoryParserWindow", "Input File", None))
        self.buttonInputFile.setText(_translate("HistoryParserWindow", "Select File", None))
        self.label_3.setText(_translate("HistoryParserWindow", "Input Folder", None))
        self.buttonInputFolder.setText(_translate("HistoryParserWindow", "Select Folder", None))
        self.groupBox_2.setTitle(_translate("HistoryParserWindow", "Output", None))
        self.label_4.setText(_translate("HistoryParserWindow", "Output File", None))
        self.buttonOutputFile.setText(_translate("HistoryParserWindow", "Select File", None))
        self.label_5.setText(_translate("HistoryParserWindow", "Output Folder", None))
        self.buttonOutputFolder.setText(_translate("HistoryParserWindow", "Select Folder", None))
        self.groupBox_3.setTitle(_translate("HistoryParserWindow", "Options", None))
        self.checkBoxSimpleNames.setText(_translate("HistoryParserWindow", "Use simple names", None))
        self.checkBoxIgnoreBetSize.setText(_translate("HistoryParserWindow", "Ignore hero bet size", None))
        self.checkBoxSiteName.setText(_translate("HistoryParserWindow", "Include site name", None))
        self.groupBox_4.setTitle(_translate("HistoryParserWindow", "Parse hand histories when", None))
        self.checkBoxHeroPlays.setText(_translate("HistoryParserWindow", "hero plays", None))
        self.checkBoxPreflopOnly.setText(_translate("HistoryParserWindow", "preflop only", None))
        self.checkBoxFlopShown.setText(_translate("HistoryParserWindow", "flop shown", None))
        self.checkBoxFlopOnly.setText(_translate("HistoryParserWindow", "flop only", None))
        self.checkBoxTurnShown.setText(_translate("HistoryParserWindow", "turn shown", None))
        self.checkBoxRiverShown.setText(_translate("HistoryParserWindow", "river shown", None))
        self.buttonParse.setText(_translate("HistoryParserWindow", "Parse", None))

